### ISSUE TITLE
Necessary external Files to run

### ISSUE THREAD

**Issue by JonathanRaiman** [francot514/Project-SimsVille#2]
Hello,

When trying to get this code to run, I'm finding that certain data files required (e.g. uigraphics.xml) do not appear to be in the Sims 1's data files (neither the Mac or PC version).

How do you get the right game files to make this executable run?

Thanks,
-Jonathan

**Comment by francot514** [comment]
Those files are not supposed to be added in source code, but i i have added a link to donwload them. 
https://www.dropbox.com/s/miy5ye6qn0tfubc/Content.rar?dl=1

**Comment by eundersander** [comment]
Hey Franco,

Working with Jonathan here. Any idea where I might find this guy?
GameData/uiscripts/ucp.uis

Although less critical, I also seem to be missing these:
gamedata/uitext/english.dir
Content/tuning.dat

Edit: perhaps the copy of the game content files we downloaded is incomplete? I see mostly .far and .iff files.

**Comment by francot514** [comment]
Yes, now fixed. But this is a prototype, so better try FreeSO
Those files are not supposed to be added in source code,  but i have added a link to donwload them.
https://www.dropbox.com/s/p2fqmxrov2r9q16/Content.rar?dl=1
