### ISSUE TITLE
How to run that game?

### ISSUE THREAD

**Issue by StraykerPL** [francot514/Project-SimsVille#7]
Hello!

I'm interested in trying out this SimsVille from the newest release, but I don't know how to run it.
I downloaded the release, unpacked it on desktop, and doubleclicked on "SimsVille.exe". The Windows Command Processor window has shown up, displaying many uncatched exceptions to folders that I don't have on my computer. Also I can't find Visual Studio solution file to open the project in IDE. The documentation will be useful in this project.

Daniel Strayker Nowak

**Comment by francot514** [comment]
Hey can you show me image of that command window errors, thanks

**Comment by StraykerPL** [comment]
![sims](https://user-images.githubusercontent.com/45916090/68712702-915c3e00-059c-11ea-849d-671b1dab56ac.PNG)

Some parts are in Polish, but exception name and message are in English. Hope it will help.

But to be sure: "w" means "in" and "wiersz" means single text line in file.

**Comment by francot514** [comment]
Do you have installed The Sims Online or The Sims, and where are those located

**Comment by StraykerPL** [comment]
I redownloaded The Sims Online files with FreeSO Launcher and now game works, but Windows Command Processor is still showing up the "False" word in first line. Is it correct?

**Comment by francot514** [comment]
Thats for allowing OpenGL if false is not allowed
